---
#########################################################
## Stop                                                ##
#########################################################

- name: Start the ZooKeeper service
  systemd:
    name: zookeeper.service
    state: stopped
    enabled: yes
  tags:
    - zookeeper_service
    - zookeeper_service-stop
