---
- name: Install Kafka service
  hosts: kafka

  pre_tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Install java
      yum:
        name: java-11-openjdk
        state: latest

  roles:
    - role: zookeeper
      become: true
      vars:
        action: "install"
        zookeeper_servers: "{{ groups['kafka'] }}"

    #- role: kafka
    #  become: true
    #  vars:
    #    action: install
    #    kafka_listener_hostname: "{{ inventory_hostname  }}"

    #- role: neo4j
    #  become: true
    #  vars:
    #    action: install
