---
- name: Enable service firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: Setup firewallPort neo4j http
  firewalld:
    port: 7474/tcp
    permanent: true
    immediate: true
    state: enabled

- name: Setup firewallPort neo4j bolt
  firewalld:
    port: 7687/tcp
    permanent: true
    immediate: true
    state: enabled
