---
###########################################
## Main module for ansible rol           ##
###########################################

- name: Load OS-specific variables {{ ansible_os_family }}
  include_vars: "{{ item }}"
  with_first_found:
    - ../vars/{{ ansible_os_family }}.yml
    - ../vars/{{ ansible_distribution_release }}.yml
    - ../vars/empty.yml
  tags:
    - always

#- name: Load OS-specific tasks {{ ansible_os_family }}
# include_vars: "{{ item }}"
#  with_first_found:
#    - ../tasks/{{ ansible_os_family }}.yml
#    - ../tasks/{{ ansible_distribution_release }}.yml
#    - ../tasks/empty.yml
#  tags:
#    - always

- name: Include OS specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install Neo4j
  ansible.builtin.include_tasks: install.yml
  when: action == "install"

- name: Uninstall Neo4j
  ansible.builtin.include_tasks: uninstall.yml
  when: action == "uninstall"

- name: Start Neo4j
  ansible.builtin.include_tasks: start.yml
  when: action == "start"

- name: Stop Neo4j
  ansible.builtin.include_tasks: stop.yml
  when: action == "stop"
