---
###########################################
## Main module for ansible rol           ##
###########################################

- name: Load OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - ../vars/{{ ansible_os_family }}.yml
    - ../vars/{{ ansible_distribution_release }}.yml
    - ../vars/empty.yml
  tags:
    - always

- name: Install kafka
  ansible.builtin.include_tasks: install.yml
  when: action == "install"

- name: Uninstall kafka
  ansible.builtin.include_tasks: uninstall.yml
  when: action == "uninstall"

- name: Start kafka
  ansible.builtin.include_tasks: start.yml
  when: action == "start"

- name: Stop kafka
  ansible.builtin.include_tasks: stop.yml
  when: action == "stop"
