---
#########################################################
## Start             f                                 ##
#########################################################

- name: Install and start the kafka service
  service:
    name: kafka
    state: started
    enabled: yes
  tags:
    - kafka_service
    - kafka-service-start
